#!/usr/bin/env python

import sys
import os 
import subprocess

amslah_path = os.path.dirname(os.path.realpath(__file__))
app_path = os.getcwd()

def print_help():
    print("""
	A M S L A H
	M S L A H A
	S L A H A M
	L A H A M S
	A H A M S L
	H A M S L A

	amslah make
		Compiles the current project.
	amslah make u
		Uploads the current project.
	amslah make clean
		Removes build files.
	amslah make o
		Runs openocd so you can attach via telnet or gdb
""")


if len(sys.argv) == 1:
    print_help()

if sys.argv[1] == "make":
    cmd = ['make','-f',os.path.join(amslah_path, 'Makefile')] + sys.argv[2:]
    subprocess.call(cmd)
else:
    print("Unknown command '%s'." % sys.argv[1])
    print_help()
